version: '3.8'
name: 'auth-test'
services:
  web:
    build: 
      context: .
      dockerfile: web.Dockerfile
    container_name: web
    volumes: 
      - ./web-app:/web-app
    working_dir: /web-app
    ports:
      - "5173:5173"
  api:
    build: 
      context: .
      dockerfile: api.Dockerfile
    container_name: api
    volumes: 
      - ./auth:/auth
    working_dir: /auth
    ports:
      - "3000:3000"